// Generated by https://quicktype.io

export interface TopLevel {
  destinations: Destination[]
  crew: Crew[]
  technology: Technology[]
}

export interface Crew {
  name: string
  images: Images
  role: string
  bio: string
}

export interface Images {
  png: string
  webp: string
}

export interface Destination {
  name: string
  images: Images
  description: string
  distance: string
  travel: string
}

export interface Technology {
  name: string
  images: TechnologyImages
  description: string
}

export interface TechnologyImages {
  portrait: string
  landscape: string
}
